/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.4.1 mustang.gltf 
Author: BadKarma™ (https://sketchfab.com/890244234)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mustang-350gt-1969-926c15df050645ea9af59346b2b249a5
Title: Mustang 350GT 1969
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/mustang.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.headlight_part_carpaint_0.geometry} material={materials.carpaint} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.headlight_01_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.headlight_00_clearglass_0.geometry} material={materials.clearglass} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.headlight_02_clearglass_0.geometry} material={materials.clearglass} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.body_2_carpaint_0.geometry} material={materials.carpaint} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.foglight_04_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.bumper_carpaint_0.geometry} material={materials.carpaint} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Bumper_front_02_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Bumper_front_00_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.bottom_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.fenders_carpaint_0.geometry} material={materials.carpaint} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Doors_carpaint_0.geometry} material={materials.carpaint} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.doors_handles_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.doors_ruber_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Window_00_windowglass_0.geometry} material={materials.windowglass} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Window_02_windowglass_0.geometry} material={materials.windowglass} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.trunk_lock_00_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.trunk_lock_03_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.back_bumper_01_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.porogi_carpaint_0.geometry} material={materials.carpaint} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.back_part_carpaint_0.geometry} material={materials.carpaint} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.windowcleaners_00_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.windowcleaners_01_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.window_chrome_00_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.windows_rubber_01_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.interior_mirror_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.interior_mirror_button_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.body_carpaint_0.geometry} material={materials.carpaint} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.gablight_04_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.gablight_05_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.gablight_00_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.gablight_06_redglass_0.geometry} material={materials.redglass} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.gablight_07_redglass_0.geometry} material={materials.redglass} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.gablight_09_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.hood_part_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_BL_05_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Window_03_windowglass_0.geometry} material={materials.windowglass} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.window_chrome_04_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Window_04_windowglass_0.geometry} material={materials.windowglass} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.window_chrome_05_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.back_lights_01_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.door_rubber_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.window_chrome_02_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.window_chrome_03_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.windows_rubber_00_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.window_chrome_01_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.back_logo_04_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.back_lights_03_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.back_lights_00_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.foglight_01_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.foglight_03_clearglass_0.geometry} material={materials.clearglass} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.foglight_rubber_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.sc_nuts_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.windowcleaners_03_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.windowcleaners_02_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.am_front_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.interior_wheel01_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.interior_part_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.windows_rubber_02_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.windows_rubber_03_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_FL_03_rim_0.geometry} material={materials.material} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_FL_00_tire_0.geometry} material={materials.tire} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.am_back_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_BL_00_tire_0.geometry} material={materials.tire} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_BL_02_rim_0.geometry} material={materials.material} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_BL_10_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.black_02_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.radiator_06_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.radiator_02_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.radiator_03_red_0.geometry} material={materials.material_8} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.radiator_04_blue_0.geometry} material={materials.blue} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.body_side_carpaint_0.geometry} material={materials.carpaint} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.body_black_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_BL_07_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.body_paint_2_carpaint_second_0.geometry} material={materials.carpaint_second} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.body_paint_3_carpaint_second_0.geometry} material={materials.carpaint_second} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.black_01_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.black_00_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_FR_00_tire_0.geometry} material={materials.tire} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_FR_01_rim_second_0.geometry} material={materials.rim_second} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_FR_02_rim_0.geometry} material={materials.material} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_FR_04_rim_0.geometry} material={materials.material} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_FR_03_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_FR_05_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_BR_00_tire_0.geometry} material={materials.tire} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_BR_03_rim_second_0.geometry} material={materials.rim_second} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_BR_01_rim_0.geometry} material={materials.material} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_BR_04_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_BR_05_rim_0.geometry} material={materials.material} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_BR_06_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_BR_07_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_BR_08_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_BR_02_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_FR_09_brakedisk_0.geometry} material={materials.brakedisk} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_FR_10_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.back_logo_05_red_0.geometry} material={materials.material_8} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.trunk_lock_01_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.trunk_lock_02_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.door_mirror_glass_mirror_0.geometry} material={materials.mirror} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.door_mirror_rubber_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.satelite_chrome_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.satelite_ruber_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.back_logo_03_red_0.geometry} material={materials.material_8} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.back_logo_06_red_0.geometry} material={materials.material_8} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.back_logo_01_gray_0.geometry} material={materials.gray} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.back_logo_02_white_0.geometry} material={materials.white} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.back_logo_00_blue_0.geometry} material={materials.blue} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.lock_hole_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.gablight_10_clearglass_0.geometry} material={materials.clearglass} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.radiator_01_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.radiator_00_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_FL_09_gold_0.geometry} material={materials.gold} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_FL_07_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_FL_06_red_0.geometry} material={materials.material_8} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_BL_09_gold_0.geometry} material={materials.gold} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_BL_08_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_BL_06_red_0.geometry} material={materials.material_8} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_BR_09_gold_0.geometry} material={materials.gold} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_BR_10_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_BR_11_red_0.geometry} material={materials.material_8} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_FR_06_gold_0.geometry} material={materials.gold} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_FR_07_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_FR_08_red_0.geometry} material={materials.material_8} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.foglight_00_orangeglass_0.geometry} material={materials.orangeglass} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_BL_01_rim_second_0.geometry} material={materials.rim_second} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_BL_11_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_BL_03_rim_0.geometry} material={materials.material} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_FL_10_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_FL_08_rim_0.geometry} material={materials.material} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.foglight_02_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_FL_02_rim_second_0.geometry} material={materials.rim_second} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.body_paint_carpaint_second_0.geometry} material={materials.carpaint_second} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.chairs_back_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.back_bumper_02_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.radiator_07_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.hood_carpaint_0.geometry} material={materials.carpaint} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.black_03_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.interior_mirror_glass_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Bumper_front_01_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_FL_01_brakedisk_0.geometry} material={materials.brakedisk} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.gablight_03_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.back_lights_04_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.back_lights_02_clearglass_0.geometry} material={materials.clearglass} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Window_01_windowglass_0.geometry} material={materials.windowglass} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.interior_wheel00_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.chairs_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.door_mirror_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.interior01_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.back_bumper_00_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.radiator_05_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_FL_04_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_FL_05_black_0.geometry} material={materials.black} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
      <mesh geometry={nodes.Whee_BL_04_chrome_0.geometry} material={materials.chrome} position={[0, -60.791, 65.043]} rotation={[Math.PI, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/mustang.gltf')
